"""Receipt verifier: schema, synthetic dataset, extractors, validator and evaluation harness."""

from receipt_verifier.builders import build_extraction
from receipt_verifier.circuit import (
    CircuitBreaker,
    CircuitOpenError,
    CircuitState,
    CircuitStatus,
    ExtractorTimeout,
    GuardedExtractor,
    run_with_timeout,
    shutdown_executor,
)
from receipt_verifier.confidence import (
    SourceQuality,
    field_confidences,
    score_extraction,
    score_field,
)
from receipt_verifier.dataset import Dataset, DatasetBundle, load_dataset, write_dataset
from receipt_verifier.extraction import (
    CRITICAL_FIELD_NAMES,
    FIELD_NAMES,
    ExtractedField,
    ExtractionResult,
    ReceiptExtractor,
)
from receipt_verifier.extractors.dummy import DummyExtractor
from receipt_verifier.harness import EvaluationReport, render_table, run_evaluation
from receipt_verifier.identifiers import (
    cuit_check_digit,
    is_valid_cbu_or_cvu,
    is_valid_cuit,
    parse_amount_text,
    parse_destination_text,
    render_amount_ars,
)
from receipt_verifier.metrics import Metrics, SampleOutcome, compute_metrics
from receipt_verifier.schema import (
    AR_TZ,
    AdversarialKind,
    DatasetManifest,
    Decision,
    Destination,
    DestinationKind,
    Issuer,
    LedgerEntry,
    ReceiptLabel,
    VerdictReason,
)
from receipt_verifier.validate import (
    DEFAULT_INJECTION_PATTERNS,
    HARD_REJECT_REASONS,
    ReasonSeverity,
    ReceiptValidator,
    ValidationPolicy,
    ValidationResult,
    decide,
    severity_of,
)

__all__ = [
    "AR_TZ",
    "CRITICAL_FIELD_NAMES",
    "DEFAULT_INJECTION_PATTERNS",
    "FIELD_NAMES",
    "HARD_REJECT_REASONS",
    "AdversarialKind",
    "CircuitBreaker",
    "CircuitOpenError",
    "CircuitState",
    "CircuitStatus",
    "Dataset",
    "DatasetBundle",
    "DatasetManifest",
    "Decision",
    "Destination",
    "DestinationKind",
    "DummyExtractor",
    "EvaluationReport",
    "ExtractedField",
    "ExtractionResult",
    "ExtractorTimeout",
    "GuardedExtractor",
    "Issuer",
    "LedgerEntry",
    "Metrics",
    "ReasonSeverity",
    "ReceiptExtractor",
    "ReceiptLabel",
    "ReceiptValidator",
    "SampleOutcome",
    "SourceQuality",
    "ValidationPolicy",
    "ValidationResult",
    "VerdictReason",
    "build_extraction",
    "compute_metrics",
    "cuit_check_digit",
    "decide",
    "field_confidences",
    "is_valid_cbu_or_cvu",
    "is_valid_cuit",
    "load_dataset",
    "parse_amount_text",
    "parse_destination_text",
    "render_amount_ars",
    "render_table",
    "run_evaluation",
    "run_with_timeout",
    "score_extraction",
    "score_field",
    "severity_of",
    "shutdown_executor",
    "write_dataset",
]
